### ISSUE TITLE
Touchpad not working on Windows

### ISSUE THREAD

**Issue by kered424** [coolstar/crostouchpad4-smbus#1]
Posting in the correct branch this time.

I just installed the latest firmware 4.22.4 and touchpad driver 4.1.6, but the touchpad does not work at all in Windows 10/11.

Can confirm that touchpad works in Ubuntu and ChromeOS Flex, but I would much prefer to run Windows. Thanks!

**Comment by coolstar** [comment]
Just tested driver 4.1.6 and it works here, though my coreboot build is old. Will update coreboot and re-test

**Comment by coolstar** [comment]
Can confirm updating coreboot broke it. Vendor / device is flipped in coreboot. Not an issue with the driver
